version: "2.1"
services:
  db:
    image: redis
    command: redis-server --appendonly yes
    volumes:
      - redis:/data

  backend:
    build: backend
    depends_on:
      - db

  nginx:
    build: nginx
    ports:
      - 8181:80
    depends_on:
      - backend

volumes:
  redis:
